"""
GENCODE gene reference validation.

The reference version is configured in reference_files/gene_info.yml
and the parquet files are regenerated by prepare_references.py.

Loads all genes_*.parquet files from reference_files/ into a single
combined lookup, so adding a new organism to gene_info.yml just works.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import pandas as pd

REFERENCE_DIR = Path(__file__).parent / "reference_files"


@lru_cache(maxsize=1)
def _load_gene_table() -> pd.DataFrame:
    files = sorted(REFERENCE_DIR.glob("genes_*.csv"))
    if not files:
        raise FileNotFoundError(
            f"No genes_*.csv files found in {REFERENCE_DIR}. "
            "Run `python scripts/prepare_references.py` to generate them."
        )
    return pd.concat([pd.read_csv(f) for f in files], ignore_index=True)


@lru_cache(maxsize=1)
def _gene_id_set() -> set[str]:
    return set(_load_gene_table()["gene_id"].values)


@lru_cache(maxsize=1)
def _gene_id_to_name() -> dict[str, str]:
    df = _load_gene_table()
    return dict(zip(df["gene_id"], df["gene_name"]))


def gene_id_exists(gene_id: str) -> bool:
    """Return True if gene_id is present in the GENCODE reference."""
    return gene_id in _gene_id_set()


def gene_symbol_matches(gene_id: str, gene_symbol: str) -> bool:
    """Return True if gene_symbol matches the GENCODE gene_name for gene_id."""
    return _gene_id_to_name().get(gene_id) == gene_symbol


def get_gene_symbol(gene_id: str) -> str | None:
    """Return the GENCODE gene_name for gene_id, or None if not found."""
    return _gene_id_to_name().get(gene_id)


def validate_var_index(gene_ids: list[str]) -> list[str]:
    """
    Validate a list of Ensembl gene IDs from an AnnData var index.
    Returns a list of invalid IDs (empty list means all valid).
    """
    valid = _gene_id_set()
    return [gid for gid in gene_ids if gid not in valid]
